Adds a @DefaultNil property wrapper
marksands/BetterCodable pull request #30
Opened 2020-12-08 03:29 UTC by moyerr

When decoding an `Optional` type, it is still possible for decoding to fail and throw an error, rather than falling back to a `nil` value. This PR addresses that issue by adding a `@DefaultNil` property wrapper, which is just a `typealias` of `@DefaultCodable` using a new `DefaultNilStrategy`. Possible README usage description below:

## @DefaultNil

Optional codable values can be frustrating in that, if decoding fails for any reason, we are often given an error instead of a `nil` value, like we might expect. 

`@DefaultNil` fixes this annoyance by defaulting decoded Optionals to nil if the Decoder is unable to decode the value.

### Usage

```Swift
struct Image: Codable {
    @DefaultNil var url: URL?
}

let json = #"{ "url": "" }"#.data(using: .utf8)!
let result = try JSONDecoder().decode(Image.self, from: json)

print(result.url) // nil
```

Without the `@DefaultNil` property wrapper here, we would get a `DecodingError.dataCorrupted(_:)` error instead.

2020-12-08 16:04 UTC, marksands commented
I don't think `@DefaultNil` is a good name here, since this is really providing a catch handler for a failed decoding. I haven't come up with a good alternative though. `@SetNilOnError`, `@FallbackToNil`, `@FailingToNil`, etc. 🤔

2020-12-08 22:15 UTC, moyerr commented
@marksands Okay yeah, I see what you mean. I like `@FallbackToNil` or `@FailsToNil`. Or what do you think about following the `Lossy` naming pattern and going with `@LossyOptional`? Whatever your preference, I'm happy to make the change 😄

2020-12-14 17:47 UTC, marksands commented
I like `LossyOptional`. Let's run with that. That gives me some ideas to make some of my other implementations more generic and flexible. 🙂 

It also might be worth adding a test that demonstrates the Lossy problem outside of URL types:

```
	func testDecodingWithBadIntegerConversion() throws {
		struct Fixture: Codable {
			@LossyOptional var a: Int?
			@LossyOptional var b: Int?
		}

		let jsonData = #"{ "a": 3.14, "b": 3 }"#.data(using: .utf8)!
		let fixture = try JSONDecoder().decode(Fixture.self, from: jsonData)
		XCTAssertNil(fixture.a)
		XCTAssertEqual(fixture.b, 3)
	}
```

2020-12-14 17:57 UTC, marksands requested changes
See also the comment I left about adding an additional fixture with another type(s).

2020-12-14 17:57 UTC, marksands commented on Tests/BetterCodableTests/DefaultNilTests.swift
> +        let urlString = "https://github.com/marksands/BetterCodable"
Let's change this to `https://website.test` per [rfc2606](https://tools.ietf.org/html/rfc2606#section-2).

2020-12-14 17:58 UTC, marksands requested changes

2020-12-14 17:58 UTC, marksands commented on Tests/BetterCodableTests/DefaultNilTests.swift
> +        let jsonData = #"{"url":""}"#.data(using: .utf8)!
Let's use something besides an empty string that demonstrates a malformed URL resulting in `nil.`

2020-12-16 01:08 UTC, moyerr commented
@marksands Thanks for the feedback! Changes addressed, and original PR description updated with name change 😃

2020-12-22 17:47 UTC, marksands approved these changes

2020-12-22 17:47 UTC, merged

2020-12-22 17:47 UTC, marksands commented
Thank you! 🙇